### ISSUE TITLE
下载配置文件后点击重启clash无法启动

### ISSUE THREAD

**Issue by Newbie-debug** [lzdnico/ClashWeb#19]
1、版本号1.6.3（已尝试1.6.1-1.6.2版本）
2、问题描述：用自带节点分组转换V2ry订阅后，下载配置文件成功，但点击重启clash无法启动，错误详情：The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.   或者就是clash无法启动
（已测试订阅没有问题，可用于CFW和CFA）
3、尝试带python和不带python的文件均无法解决问题
4、本地移动500M和联通4G网络均无法解决上述问题
5、更换内核仍无法解决

**Comment by lzdnico** [comment]
需要更多信息。可以联系tg
