### ISSUE TITLE
修改端口后无法应用到系统代理

### ISSUE THREAD

**Issue by sengoku-f** [lzdnico/ClashWeb#20]
修改`Profile/defaultconfig/default.yaml`端口为`1080`后clash默认启动为`1080`
但是设置为系统代理还是原来的`7890`

**Comment by zhaokelei** [comment]
默认配置文件和你再用的配置文件端口都改成一致，再重启clashweb

**Comment by sengoku-f** [comment]
> 默认配置文件和你再用的配置文件端口都改成一致，再重启clashweb

试过了不行，应该是`bug`吧

**Comment by zhaokelei** [comment]
我这边没问题 也有可能是端口占用吧

**Comment by sengoku-f** [comment]
> 我这边没问题 也有可能是端口占用吧

不是占用吧，我手动设置系统代理是可用的，日志里面也看得到请求，就是用clash设置系统代理固定是7890

**Comment by sengoku-f** [comment]
找到原因了，系统代理的端口`7890`默认写死在`/bat/setsys.bat`中
修改`Profile/defaultconfig/default.yaml`端口为`1080`后，需要同步修改`/bat/setsys.bat`中的端口为`1080`
希望可以优化一下，自动读取`Profile/defaultconfig/default.yaml`中的端口

**Comment by lzdnico** [comment]
感谢反馈，下个版本优化

**Comment by sengoku-f** [comment]
> 感谢反馈，下个版本优化

自己写了个 `bat`，我自己的电脑测试没问题
加在 `./bat/setsys.bat` 的开头
```
for /F "tokens=1,2 delims=:" %%a in ('findstr /x /I "^port:.*[0-9].*$" ".\Profile\defaultconfig\default.yaml"') do set "http_port=%%~nxb"
set http_port=%http_port: =%
```

**Comment by lzdnico** [comment]
> > 感谢反馈，下个版本优化
> 
> 自己写了个 `bat`，我自己的电脑测试没问题
> 加在 `./bat/setsys.bat` 的开头
> 
> ```
> for /F "tokens=1,2 delims=:" %%a in ('findstr /x /I "^port:.*[0-9].*$" ".\Profile\defaultconfig\default.yaml"') do set "http_port=%%~nxb"
> set http_port=%http_port: =%
> cd ./App
> sysproxy global 127.0.0.1:%http_port% localhost;127.*;10.*
> ```

可用，感谢！
