### ISSUE TITLE
请求增加“双击任务栏图标打开切换节点”功能

### ISSUE THREAD

**Issue by vhvg** [lzdnico/ClashWeb#22]
切换节点为稍高频功能，请求增加双击打开功能

**Comment by lzdnico** [comment]
- [ ]

**Comment by lzdnico** [comment]
好思路

**Comment by lzdnico** [comment]
[
[patch.zip](https://github.com/lzdnico/ClashWeb/files/4681465/patch.zip)
](url)

**Comment by Doraemon2020** [comment]
请问“检查状态”是做什么用，我这里没啥反应

**Comment by lzdnico** [comment]
> 请问“检查状态”是做什么用，我这里没啥反应

win10打开系统通知。用来查看Clash时候开启，系统代理是否开启

**Comment by Doraemon2020** [comment]
> > 请问“检查状态”是做什么用，我这里没啥反应
> 
> win10打开系统通知。用来查看Clash时候开启，系统代理是否开启

没法把托管图标做成实时显示开关状态吗？

**Comment by lzdnico** [comment]
> > > 请问“检查状态”是做什么用，我这里没啥反应
> > 
> > 
> > win10打开系统通知。用来查看Clash时候开启，系统代理是否开启
> 
> 没法把托管图标做成实时显示开关状态吗？

不会:)

**Comment by vhvg** [comment]
> [patch.zip](https://github.com/lzdnico/ClashWeb/files/4681465/patch.zip)
> 下载解压到主目录，试试看

感谢，替换两文件后已成功实现功能
