### ISSUE TITLE
控制栏菜单简化

### ISSUE THREAD

**Issue by OpenWaygate** [lzdnico/ClashWeb#24]
系统代理和控制后台都只有两种状态, 能不能把这两个的子菜单去掉, 直接显示状态👇, 点击两者即可切换状态.
```
系统代理 √
控制后台 ×
```
![image](https://user-images.githubusercontent.com/27287694/82748978-b0a01780-9dd8-11ea-9def-4913bf45b1d9.png)

**Comment by zhaokelei** [comment]
老哥 你任务栏监控是什么软件

**Comment by OpenWaygate** [comment]
> 老哥 你任务栏监控是什么软件

很有眼光😎 [XMeters](https://entropy6.com/xmeters/download/)

**Comment by zhaokelei** [comment]
感谢

**Comment by lzdnico** [comment]
没有思路，无法做到。
