### ISSUE TITLE
打开面板=>代理 策略组的节点颜色与下方测速的颜色对应

### ISSUE THREAD

**Issue by OpenWaygate** [lzdnico/ClashWeb#28]
webui的 打开面板=>代理 有两部分, 策略组和代理
代理部分的节点测速后有四种颜色, 绿色 橙色 红色 灰色, 延迟依次升高
而策略组部分的节点只有两种颜色, 透明和红色, 红色对应的测速结果的灰色

能否将策略组部分节点的颜色统一到代理部分节点的颜色, 并按绿-> 橙-> 红-> 灰排序?
谢谢

**Comment by lzdnico** [comment]
移步ClashDashboard
