### ISSUE TITLE
建议添加“隐藏任务栏托盘图标”的选项

### ISSUE THREAD

**Issue by mobilefish** [lzdnico/ClashWeb#32]
每次启动时都会出现状态提示，能否添加开关不提示状态；另外是否还可以添加windows下隐藏任务栏右下角小猫咪图标的 快捷键

**Comment by sengoku-f** [comment]
> 每次启动时都会出现状态提示，能否添加开关不提示状态；另外是否还可以添加windows下隐藏任务栏右下角小猫咪图标的快捷键

关闭 windows 通知中心,并隐藏任务栏图标

**Comment by lzdnico** [comment]
感谢反馈
