### ISSUE TITLE
新版本，无法自动设置Socks5 代理

### ISSUE THREAD

**Issue by yzjmxy** [lzdnico/ClashWeb#33]
新的版本似乎无法正确的读取配置文件，并设置本地代理端口。
![snipaste_20200816_140837](https://user-images.githubusercontent.com/39520103/90329732-d3a62600-dfd9-11ea-9523-c02cc7b7fd09.png)
![snipaste_20200816_140809](https://user-images.githubusercontent.com/39520103/90329734-d56fe980-dfd9-11ea-879b-bb5c74a77033.png)
![snipaste_20200816_140823](https://user-images.githubusercontent.com/39520103/90329735-d6088000-dfd9-11ea-9211-c4006b3d189e.png)

**Comment by sengoku-f** [comment]
新版本已经 mix 为7890

> 新的版本似乎无法正确的读取配置文件，并设置本地代理端口。
> ![snipaste_20200816_140837](https://user-images.githubusercontent.com/39520103/90329732-d3a62600-dfd9-11ea-9523-c02cc7b7fd09.png)
> ![snipaste_20200816_140809](https://user-images.githubusercontent.com/39520103/90329734-d56fe980-dfd9-11ea-879b-bb5c74a77033.png)
> ![snipaste_20200816_140823](https://user-images.githubusercontent.com/39520103/90329735-d6088000-dfd9-11ea-9211-c4006b3d189e.png)

**Comment by lzdnico** [comment]
查看帮助，常见问题，如何修改sock/http代理端口。 另外，sock和http端口统一为7890。

**Comment by yzjmxy** [comment]
> 查看帮助，常见问题，如何修改sock/http代理端口。 另外，sock和http端口统一为7890。
啊这……就十分尴尬了。 
感谢作者
愿意回答我这么小白的问题

**Comment by yzjmxy** [comment]
> 查看帮助，常见问题，如何修改sock/http代理端口。 另外，sock和http端口统一为7890。

啊这……就十分尴尬了。
感谢作者
愿意回答我这么小白的问题

**Comment by yzjmxy** [comment]
> 新版本已经 mix 为7890
> 
> > 新的版本似乎无法正确的读取配置文件，并设置本地代理端口。
> > ![snipaste_20200816_140837](https://user-images.githubusercontent.com/39520103/90329732-d3a62600-dfd9-11ea-9523-c02cc7b7fd09.png)
> > ![snipaste_20200816_140809](https://user-images.githubusercontent.com/39520103/90329734-d56fe980-dfd9-11ea-879b-bb5c74a77033.png)
> > ![snipaste_20200816_140823](https://user-images.githubusercontent.com/39520103/90329735-d6088000-dfd9-11ea-9211-c4006b3d189e.png)

啊这……就十分尴尬了。
万分感谢

**Comment by akw5454521** [comment]
我的配置文件也没改成mix，在clash页面和楼主的情况一样显示为0，但是使用7980端口可以正常代理

**Comment by lzdnico** [comment]
@akw5454521 正常，dashboard得Bug，等上游更新
