### ISSUE TITLE
最新的版本win报毒

### ISSUE THREAD

**Issue by markwhitey** [lzdnico/ClashWeb#36]
Trojan：Script / Wacatac.B！ml
被Microsoft Defender防病毒软件检测到
别名： 没有关联的别名

概要
Windows Defender防病毒软件可以检测并消除此威胁。

这种威胁可以在您的PC上执行恶意黑客选择的多种操作。

了解恶意软件如何在您的PC上传播。

**Comment by lzdnico** [comment]
不放心的话，建议用ClashWeb.ahk自行生成.exe
