### ISSUE TITLE
能否以非管理员权限启动程序？

### ISSUE THREAD

**Issue by timeneverdie** [lzdnico/ClashWeb#38]
最近两个版本必须以管理员权限启动程序才给用。

应该设定为仅某些功能需要启用管理员权限（比如旧版本在设置开机自启动时才会请求管理员权限）。

**Comment by xqXQzzz1** [comment]
@timeneverdie 如果单个程序管理员启动话，clashweb本身就会对clash.exe缺少控制，毕竟clashweb是非管理员权限的，clash.exe是需要管理员权限的，可能改的比较多

**Comment by lzdnico** [comment]
建议自行删除ClashWeb.ahk 前14行代码并生成ClashWeb.exe

**Comment by lzdnico** [comment]
![image](https://user-images.githubusercontent.com/12426615/103843377-b120c080-50d2-11eb-97cf-f12c2947f3e7.png)
生成示意图
