### ISSUE TITLE
在使用了在线订阅转换后，ClashWeb下载订阅时出现乱码

### ISSUE THREAD

**Issue by HXHGTS** [lzdnico/ClashWeb#39]
使用了在线订阅转换，然后将订阅链接放入ClashWeb会出现乱码，但同样的订阅链接放入Clash For Windows与Clash For Android都是正常的，感觉是字符编码的问题，希望修复一下，谢谢

**Comment by lzdnico** [comment]
https://t.me/clashwebgroup

**Comment by lzdnico** [comment]
进群私聊管理提供订阅测试
