### ISSUE TITLE
打不开网页面板

### ISSUE THREAD

**Issue by ag163** [lzdnico/ClashWeb#4]
打不开网页面版

**Comment by gang4399** [comment]
@ag163 你试试试用32M自带py库的那个 by@B_orC

**Comment by ag163** [comment]
> @ ag163你尝试试用32M自带py库的那个by @ B_orC

我用的就是32m的

**Comment by ag163** [comment]
> @ ag163你尝试试用32M自带py库的那个by @ B_orC

10.3m的控制台打不开

**Comment by gang4399** [comment]
你用的啥浏览器？

**Comment by ag163** [comment]
> 你用的啥浏览器？

谷歌浏览器

**Comment by ag163** [comment]
> 你用的啥浏览器？

![2020-03-14_185809](https://user-images.githubusercontent.com/58593096/76680717-e9c44a80-6625-11ea-8a7a-23ebe437581f.png)

**Comment by lzdnico** [comment]
配置文件问题，或者清除浏览器缓存

**Comment by ag163** [comment]
> 配置文件问题，或者清除浏览器缓存

可以了，感谢！
