### ISSUE TITLE
更新完2.0版本后clash无法启动

### ISSUE THREAD

**Issue by ZerOri** [lzdnico/ClashWeb#45]
RT，配置重显示启动成功，但状态栏却显示clash未启动

**Comment by lzdnico** [comment]
@ZerOri python.exe出现错误

**Comment by lzdnico** [comment]
@lzdnico 已修复，重新下载

**Comment by xiaoyao2021** [comment]
你好，win7 32位系统无法启动clash,无法打开控制台！

**Comment by lzdnico** [comment]
[python.zip](https://github.com/lzdnico/ClashWeb/files/6077260/python.zip)
下载替换掉python.exe试试

**Comment by lzdnico** [comment]
> 你好，win7 32位系统无法启动clash,无法打开控制台！

如上

**Comment by xiaoyao2021** [comment]
试了，不行

**Comment by lzdnico** [comment]
@xiaoyao2021 请替换测试老版本python.exe

**Comment by xiaoyao2021** [comment]
试了1.6.6，不行
