### ISSUE TITLE
配置文件无法载入

### ISSUE THREAD

**Issue by ZerOri** [lzdnico/ClashWeb#46]
![QQ截图20210305012757](https://user-images.githubusercontent.com/46775615/110004231-28c93f80-7d52-11eb-8b1d-c633e6525532.png)

RT，添加订阅链接时出现了上面的弹窗，导致订阅无法更新启用。clashweb 2.0版本

**Comment by lzdnico** [comment]
描述不详

**Comment by ZerOri** [comment]
> 描述不详

hhh，问题找到了，是配置文件的文件名用了标点【 - 】，导致不能识别，已解决。
