### ISSUE TITLE
能否推出64位版本呢？以及一些其它的问题

### ISSUE THREAD

**Issue by MysteryMulberry** [lzdnico/ClashWeb#47]
现在大多数人的电脑都已是64位的系统了，再去使用32位的程序会有一定的性能损失~
另外，当导入的节点较多时（比如https://proxypoolss.tk/里的连接），节点切换界面就成了空白，，而隔壁clash客户端导入大量节点后切换时虽然卡 但还能用~希望web端这边能优化下，谢谢大佬！

**Comment by xqXQzzz1** [comment]
@MysteryMulberry 本身不就是64位的吗？

**Comment by xqXQzzz1** [comment]
@MysteryMulberry 节点切换界面使用yard，1314个节点显示正常，不过比较卡
