### ISSUE TITLE
功能请求：定时更新配置文件以及ruleset和proxy provider

### ISSUE THREAD

**Issue by lunjielee** [lzdnico/ClashWeb#48]
@lzdnico ，你好，

配置文件的ruleset部分尽管可以设置86400秒更新一次，但是在网页端的上一次更新时间不会有变化。同时配置文件本身和proxy provider也没有任何设置自动更新的入口

**Comment by lzdnico** [comment]
定时更新配置文件暂替方案： https://t.me/c/1441637801/553

**Comment by lunjielee** [comment]
呃，我无法查看这条消息

**Comment by lzdnico** [comment]
@lunjielee https://t.me/clashwebgroup/7588

**Comment by lunjielee** [comment]
好的，十分感谢
