### ISSUE TITLE
subconverter.exe -cfw的配置文件在哪里?

### ISSUE THREAD

**Issue by lon91ong** [lzdnico/ClashWeb#49]
想要用国内镜像`raw.sevencdn.com`替换`raw.githubusercontent.com`提高一下速度

**Comment by lzdnico** [comment]
App\subconverter  文件目录下，具体使用移步subconverter项目。

**Comment by lzdnico** [comment]
只有检测到你的订阅地址 为本地地址时，ClashWeb才会调用内置subconverter， 否则直接获取远程地址内容

**Comment by lon91ong** [comment]
`App\subconverter`路径下好多配置文件，相同的文件也存在与多个文件夹
就是本地订阅的情况下，不清楚具体它调用了哪个

**Comment by lzdnico** [comment]
pref.yml , 具体使用移步subconverter项目。

> `App\subconverter`路径下好多配置文件，相同的文件也存在与多个文件夹
> 就是本地订阅的情况下，不清楚具体它调用了哪个
