### ISSUE TITLE
请求优化配置文件管理系统

### ISSUE THREAD

**Issue by txyyh** [lzdnico/ClashWeb#5]
1. **请求支持无限数量的配置文件**
2. 如可能希望配置文件切换界面可以和cfw一样，块状显示每个配置文件，方便查看与切换

辛苦了~

**Comment by lzdnico** [comment]
@txyyh 根据投票，大部分人不超过3个配置文件。而本项目已经做了6个的显示。

对应代码在api.py profiles函数下面，欢迎提交PR

一种无限配置文件的方法可以参考上传gist页面，通过弹出文件夹来选择。
