### ISSUE TITLE
有遇到过退出软件电脑不能上网，打开又可以上网的问题吗？

### ISSUE THREAD

**Issue by jaan-git** [lzdnico/ClashWeb#50]
win7系统上，运行状态
![无标题.png](https://img01.sogoucdn.com/app/a/100520146/e961f98e70592272350171693c468ac5)

**Comment by lzdnico** [comment]
退出后，观察：控制面板\网络和 Internet\网络连接  里是否有Clash网卡

**Comment by jaan-git** [comment]
退出就没有Clash网卡了

**Comment by lzdnico** [comment]
> 退出就没有Clash网卡了

退出后， 观察系统代理是否正常关闭

**Comment by jaan-git** [comment]
> > 退出就没有Clash网卡了
> 
> 退出后， 观察系统代理是否正常关闭

上面截图系统代理一直关闭状态，退出后也是关闭；
我把软件里面的系统代理开启后也是一样退出后不能上网，退出后也显示没有系统代理
![Snipaste_2021-03-24_11-09-43.png](https://img03.sogoucdn.com/app/a/100520146/f98fbdf9b8add9e5830ff9652bf993e2)

**Comment by lzdnico** [comment]
> > > 退出就没有Clash网卡了
> > 
> > 
> > 退出后， 观察系统代理是否正常关闭
> 
> 上面截图系统代理一直关闭状态，退出后也是关闭；
> 我把软件里面的系统代理开启后也是一样退出后不能上网，退出后也显示没有系统代理
> ![Snipaste_2021-03-24_11-09-43.png](https://camo.githubusercontent.com/6d38cc3bcfc9c587419afc1c49650798fce55cee3230bae45af61468aa0f33ac/68747470733a2f2f696d6730332e736f676f7563646e2e636f6d2f6170702f612f3130303532303134362f6639386662646639623861646439653538333066663936353262663939336532)

原因不详

**Comment by jaan-git** [comment]
重启电脑后恢复正常，先关了
