### ISSUE TITLE
更改端口和代理模式后无法保存的问题

### ISSUE THREAD

**Issue by kylyzhh** [lzdnico/ClashWeb#7]
更改配置文件代理端口和代理模式后重启clash，会恢复到默认的状态，查看配置文件是已经修改了的，但是进控制面板看到还是默认的端口与代理模式。每次重新打开软件后也是同样的状况，很影响使用，希望能够修复，谢谢。

**Comment by lzdnico** [comment]
@kylyzhh 请修改Profile/defaultconfig/default.yaml，并修改api/default.py

**Comment by kylyzhh** [comment]
@lzdnico Profile/defaultconfig/default.yaml这个文件已经是修改后的状态，api/default.py没有代理端口修改，只有控制面板端口

**Comment by lzdnico** [comment]
@kylyzhh 无图无真相

**Comment by kylyzhh** [comment]
该问题确实存在，在多个不同端口配置文件切换时，无法切换到当前配置文件的端口和模式，切换后打开控制面板仍是之前的端口和模式。问题视频我会抽空录制后上传供参考。

**Comment by lzdnico** [comment]
@kylyzhh 端口与用户配置文件无关，仅仅与default.yaml定义的端口有关

**Comment by kylyzhh** [comment]
@lzdnico 那么代理模式呢？

**Comment by lzdnico** [comment]
@kylyzhh 何不自己动手试试

**Comment by kylyzhh** [comment]
@lzdnico 就是试了不行

**Comment by lzdnico** [comment]
@kylyzhh 端口、代理模式、外部ui与用户配置文件无关，仅仅与default.yaml定义的端口有关

**Comment by kylyzhh** [comment]
好的谢谢 @lzdnico
