### ISSUE TITLE
启动Clash失败

### ISSUE THREAD

**Issue by jack01-make** [lzdnico/ClashWeb#8]
第一次用，配置成功后，重启不成功，页面如下。我在面板启动和在程序启动，都失败

**Comment by jack01-make** [comment]
![image](https://user-images.githubusercontent.com/61861432/78001224-f7890800-7367-11ea-9e7f-45db6667b71a.png)

**Comment by jack01-make** [comment]
我有用Clash for windows, 刚刚都退出程序了，不知道还有没有影响

**Comment by lzdnico** [comment]
需要更多信息。

**Comment by jack01-make** [comment]
之前卸载没用，这几天又重新下载安装后能用了
