### ISSUE TITLE
Hope can select node in the speed test area.

### ISSUE THREAD

**Issue by chaoscard** [lzdnico/ClashWeb#9]
希望能在测速区域直接选择节点
如题，如果节点过多的话，很难选到自己想要的节点
[![GUAr1H.md.png](https://s1.ax1x.com/2020/04/03/GUAr1H.md.png)](https://imgchr.com/i/GUAr1H)
[![GUAscd.md.png](https://s1.ax1x.com/2020/04/03/GUAscd.md.png)](https://imgchr.com/i/GUAscd)

**Comment by gang4399** [comment]
URL延迟组？不支持手动选的啊。你可以再分下组别便于管理和分流。比如按地区和级别再分下组之类的

**Comment by lzdnico** [comment]
无法实现，移步clash dashboard

**Comment by xqXQzzz1** [comment]
建议使用yacd
